
# -*- coding: utf-8 -*-
#  Generated by Django 2.0.2 on 2018-02-13 19:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None)),
        ),
    ]
