# Generated by Django 2.0.2 on 2018-02-17 09:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='We',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'О Нас',
                'verbose_name_plural': 'О Нас',
            },
        ),
    ]
