# Generated by Django 2.0.2 on 2018-02-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180212_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complex_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complex_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ComplexProduct')),
            ],
            options={
                'verbose_name': 'Фотография сложного товара',
                'verbose_name_plural': 'Фотографии сложного товара',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товара'},
        ),
    ]
