# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-02-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180213_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
