# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-02-14 13:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180214_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexproduct',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None),
        ),
    ]
