# Generated by Django 2.0.2 on 2018-02-14 13:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180214_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexproduct',
            name='opt_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
