# Generated by Django 2.0.2 on 2018-02-14 13:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_complexproduct_opt_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opt_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
